// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-9xYDnA9AOFDvEtNJyk6WMHNKdHcsME',
    appId: '1:388307812984:web:0a2bc0c25986013a80e38d',
    messagingSenderId: '388307812984',
    projectId: 'projetpfe-5c0c5',
    authDomain: 'projetpfe-5c0c5.firebaseapp.com',
    storageBucket: 'projetpfe-5c0c5.appspot.com',
    measurementId: 'G-MZDN7DWDYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-4JUzDjwf-0_UYbNx_GWq6hxtNk5fMfA',
    appId: '1:388307812984:android:c3fd41700d8a651180e38d',
    messagingSenderId: '388307812984',
    projectId: 'projetpfe-5c0c5',
    storageBucket: 'projetpfe-5c0c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQSgF7IOLNNiOQh2KtpuJ_0Taq63AyW14',
    appId: '1:388307812984:ios:35bff1528f8aa53e80e38d',
    messagingSenderId: '388307812984',
    projectId: 'projetpfe-5c0c5',
    storageBucket: 'projetpfe-5c0c5.appspot.com',
    iosBundleId: 'com.example.projetpfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQSgF7IOLNNiOQh2KtpuJ_0Taq63AyW14',
    appId: '1:388307812984:ios:35bff1528f8aa53e80e38d',
    messagingSenderId: '388307812984',
    projectId: 'projetpfe-5c0c5',
    storageBucket: 'projetpfe-5c0c5.appspot.com',
    iosBundleId: 'com.example.projetpfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1-9xYDnA9AOFDvEtNJyk6WMHNKdHcsME',
    appId: '1:388307812984:web:eb45fc68d8d7e3a780e38d',
    messagingSenderId: '388307812984',
    projectId: 'projetpfe-5c0c5',
    authDomain: 'projetpfe-5c0c5.firebaseapp.com',
    storageBucket: 'projetpfe-5c0c5.appspot.com',
    measurementId: 'G-VMLK62FF8Z',
  );

}